
CREATE TABLE IF NOT EXISTS Training (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    platform VARCHAR(255) NOT NULL,
    hours INT NOT NULL,
    author_id BIGINT NOT NULL,
    CONSTRAINT fk_training_author FOREIGN KEY (author_id) REFERENCES Author (id)
);

CREATE TABLE IF NOT EXISTS AUTHORS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

ALTER TABLE AUTHORS ADD CONSTRAINT fk_author_training FOREIGN KEY (training_id) REFERENCES TRAININGS (id);


CREATE TABLE IF NOT EXISTS EMPLOYEES (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);
